import { createFileRoute, useNavigate, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  Download,
  ArrowLeft,
  Users,
  AlertOctagon,
  ListChecks,
  Repeat,
  FileText,
  Sparkles,
} from "lucide-react";

import { AppHeader } from "@/components/AppHeader";
import { FindingCard } from "@/components/FindingCard";
import { Button } from "@/components/ui/button";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import { useStudy } from "@/lib/store";
import { SEVERITY_ORDER } from "@/lib/types";
import { downloadText, formatTs, studyToMarkdown } from "@/lib/export";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/report")({
  head: () => ({
    meta: [
      { title: "Findings report — LENS" },
      {
        name: "description",
        content: "Usability findings report generated by LENS.",
      },
    ],
  }),
  component: ReportPage,
});

function ReportPage() {
  const navigate = useNavigate();
  const study = useStudy((s) => s.study);

  const totalFindings = useMemo(
    () => study.sessions.reduce((a, s) => a + (s.findings?.length ?? 0), 0),
    [study],
  );
  const criticalCount = useMemo(
    () =>
      study.sessions.reduce(
        (a, s) =>
          a + (s.findings?.filter((f) => f.severity === "Critical").length ?? 0),
        0,
      ),
    [study],
  );
  const frictionMoments = useMemo(
    () => study.sessions.reduce((a, s) => a + (s.report?.frictionCount ?? 0), 0),
    [study],
  );

  if (study.sessions.length === 0) {
    return (
      <div className="min-h-dvh bg-background">
        <AppHeader current={3} />
        <div className="container-page py-20 text-center">
          <p className="text-muted-foreground">No sessions analyzed yet.</p>
          <Button asChild className="mt-4">
            <Link to="/">Start a study</Link>
          </Button>
        </div>
      </div>
    );
  }

  const onExport = () => {
    const md = studyToMarkdown(study);
    downloadText(`LENS-report-${Date.now()}.md`, md);
  };

  return (
    <div className="min-h-dvh bg-background">
      <AppHeader current={3} />

      {/* Header */}
      <section className="border-b border-border bg-surface">
        <div className="container-page py-8 md:py-10">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div className="min-w-0">
              <p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">
                Findings report
              </p>
              <h1 className="mt-2 font-display text-3xl font-semibold text-ink">
                Study results
              </h1>
              <p className="mt-1 text-sm text-muted-foreground line-clamp-2 max-w-2xl">
                {study.context}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                onClick={() => navigate({ to: "/" })}
                className="gap-2"
              >
                <ArrowLeft className="h-4 w-4" /> New study
              </Button>
              <Button onClick={onExport} className="gap-2">
                <Download className="h-4 w-4" /> Export Markdown
              </Button>
            </div>
          </div>

          {/* Metrics */}
          <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Metric icon={<Users className="h-4 w-4" />} label="Sessions" value={study.sessions.length} />
            <Metric
              icon={<ListChecks className="h-4 w-4" />}
              label="Findings"
              value={totalFindings}
            />
            <Metric
              icon={<AlertOctagon className="h-4 w-4" />}
              label="Critical"
              value={criticalCount}
              tone={criticalCount > 0 ? "critical" : "neutral"}
            />
            <Metric
              icon={<Repeat className="h-4 w-4" />}
              label="Friction moments"
              value={frictionMoments}
            />
          </div>
        </div>
      </section>

      <div className="container-page py-8">
        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="bg-surface-subtle">
            <TabsTrigger value="overview" className="gap-2">
              <Sparkles className="h-3.5 w-3.5" /> Overview
            </TabsTrigger>
            {study.sessions.map((s) => (
              <TabsTrigger key={s.id} value={s.id}>
                {s.participantId}
              </TabsTrigger>
            ))}
          </TabsList>

          {/* Overview tab */}
          <TabsContent value="overview" className="mt-6 space-y-6">
            <OverviewTab />
          </TabsContent>

          {/* Session tabs */}
          {study.sessions.map((s) => (
            <TabsContent key={s.id} value={s.id} className="mt-6">
              <SessionTab sessionId={s.id} />
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </div>
  );
}

function Metric({
  icon,
  label,
  value,
  tone = "neutral",
}: {
  icon: React.ReactNode;
  label: string;
  value: number | string;
  tone?: "neutral" | "critical";
}) {
  return (
    <div className="surface-card p-4">
      <div className="flex items-center justify-between">
        <span
          className={cn(
            "grid h-7 w-7 place-items-center rounded-md",
            tone === "critical"
              ? "bg-critical-soft text-critical"
              : "bg-primary/10 text-primary",
          )}
        >
          {icon}
        </span>
      </div>
      <p className="mt-3 font-display text-2xl font-semibold text-ink tabular-nums">
        {value}
      </p>
      <p className="text-xs text-muted-foreground">{label}</p>
    </div>
  );
}

function OverviewTab() {
  const study = useStudy((s) => s.study);

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
      <div className="space-y-6">
        <section className="surface-elevated p-6">
          <h2 className="font-display text-lg font-semibold text-ink">
            Executive summary
          </h2>
          {study.crossSession?.summary ? (
            <p className="mt-3 text-sm leading-relaxed text-ink">
              {study.crossSession.summary}
            </p>
          ) : study.sessions.length === 1 ? (
            <p className="mt-3 text-sm leading-relaxed text-ink">
              {study.sessions[0].report?.summary ||
                "No summary was generated for this session."}
            </p>
          ) : (
            <p className="mt-3 text-sm text-muted-foreground">
              Cross-session synthesis was not generated.
            </p>
          )}
        </section>

        {study.crossSession?.recurringPatterns?.length ? (
          <section className="surface-elevated p-6">
            <h2 className="font-display text-lg font-semibold text-ink flex items-center gap-2">
              <Repeat className="h-4 w-4 text-primary" /> Recurring patterns
            </h2>
            <ul className="mt-4 space-y-3">
              {study.crossSession.recurringPatterns.map((p, i) => (
                <li
                  key={i}
                  className="rounded-lg border border-border bg-surface p-4"
                >
                  <div className="flex items-start justify-between gap-3">
                    <p className="font-medium text-ink">{p.pattern}</p>
                    <span
                      className={cn(
                        "inline-flex items-center rounded-md border px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wider shrink-0",
                        p.severity === "Critical" &&
                          "bg-critical-soft text-critical border-critical/30",
                        p.severity === "Major" &&
                          "bg-major-soft text-major-foreground border-major/40",
                        p.severity === "Minor" &&
                          "bg-minor-soft text-minor border-minor/30",
                      )}
                    >
                      {p.severity}
                    </span>
                  </div>
                  <p className="mt-2 text-xs text-muted-foreground">
                    Seen in: {p.sessions.join(", ")}
                  </p>
                </li>
              ))}
            </ul>
          </section>
        ) : null}

        {study.crossSession?.highlights?.length ? (
          <section className="surface-elevated p-6">
            <h2 className="font-display text-lg font-semibold text-ink">
              Highlights
            </h2>
            <ul className="mt-3 space-y-2">
              {study.crossSession.highlights.map((h, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-ink leading-relaxed"
                >
                  <span className="mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-gold" />
                  {h}
                </li>
              ))}
            </ul>
          </section>
        ) : null}
      </div>

      <aside className="space-y-4">
        <div className="surface-elevated p-5">
          <h3 className="font-display text-sm font-semibold text-ink">
            Participants
          </h3>
          <ul className="mt-3 space-y-2">
            {study.sessions.map((s) => (
              <li
                key={s.id}
                className="flex items-center gap-3 rounded-md border border-border bg-surface p-2.5"
              >
                <span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground text-xs font-semibold">
                  {s.participantId.slice(0, 3)}
                </span>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-ink truncate">
                    {s.participantId}
                  </p>
                  <p className="text-[11px] text-muted-foreground truncate">
                    {s.findings?.length ?? 0} findings ·{" "}
                    {s.findings?.filter((f) => f.severity === "Critical").length ?? 0} critical
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </aside>
    </div>
  );
}

function SessionTab({ sessionId }: { sessionId: string }) {
  const session = useStudy((s) =>
    s.study.sessions.find((x) => x.id === sessionId),
  );
  const [transcriptOpen, setTranscriptOpen] = useState(false);

  if (!session) return null;

  if (session.status === "error") {
    return (
      <div className="surface-elevated p-6">
        <p className="text-sm text-destructive">
          Analysis failed for {session.participantId}.
        </p>
        <p className="mt-2 text-xs text-muted-foreground">
          {session.errorMessage}
        </p>
      </div>
    );
  }

  const sortedFindings = [...(session.findings ?? [])].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity],
  );

  return (
    <div className="space-y-6">
      {/* Summary */}
      <section className="surface-elevated p-6">
        <div className="flex items-start gap-4">
          <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground text-sm font-semibold">
            {session.participantId.slice(0, 3)}
          </span>
          <div className="min-w-0 flex-1">
            <h2 className="font-display text-xl font-semibold text-ink">
              {session.participantId}
            </h2>
            {session.note && (
              <p className="text-xs text-muted-foreground italic">
                {session.note}
              </p>
            )}
            <p className="mt-3 text-sm leading-relaxed text-ink">
              {session.report?.summary || "No summary."}
            </p>
          </div>
        </div>
      </section>

      {/* Findings */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="font-display text-lg font-semibold text-ink">
            Findings ({sortedFindings.length})
          </h3>
          <p className="text-xs text-muted-foreground">
            Sorted Critical → Major → Minor
          </p>
        </div>
        {sortedFindings.length === 0 ? (
          <div className="surface-card p-6 text-center text-sm text-muted-foreground">
            No findings detected in this session.
          </div>
        ) : (
          <div className="space-y-3">
            {sortedFindings.map((f) => (
              <FindingCard key={f.id} finding={f} />
            ))}
          </div>
        )}
      </section>

      {/* Transcript */}
      <section className="surface-elevated overflow-hidden">
        <button
          onClick={() => setTranscriptOpen((o) => !o)}
          className="flex w-full items-center justify-between gap-3 p-5 text-left"
        >
          <div className="flex items-center gap-3">
            <FileText className="h-4 w-4 text-primary" />
            <h3 className="font-display text-base font-semibold text-ink">
              Full transcript
            </h3>
            <span className="text-xs text-muted-foreground">
              {session.transcript?.length ?? 0} segments · friction highlighted
            </span>
          </div>
          <span className="text-xs text-muted-foreground">
            {transcriptOpen ? "Hide" : "Show"}
          </span>
        </button>
        {transcriptOpen && (
          <div className="border-t border-border max-h-[480px] overflow-y-auto bg-surface-subtle/30 p-5">
            <ol className="space-y-1.5 text-sm">
              {(session.transcript ?? []).map((t, i) => (
                <li
                  key={i}
                  className={cn(
                    "flex gap-3 rounded px-2 py-1 leading-relaxed",
                    t.frictionFlag &&
                      "bg-gold-soft border-l-2 border-gold pl-2",
                  )}
                >
                  <span className="font-mono text-[11px] text-muted-foreground tabular-nums shrink-0 pt-0.5">
                    {formatTs(t.start)}
                  </span>
                  <span className="text-ink">{t.text}</span>
                </li>
              ))}
              {(session.transcript ?? []).length === 0 && (
                <li className="text-muted-foreground text-xs">
                  No transcript was returned.
                </li>
              )}
            </ol>
          </div>
        )}
      </section>
    </div>
  );
}
